version: "3.9"
services:
  next_movie:
    container_name: next_movie
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3003:3000"
    volumes:
      - /app/node_modules
      - .:/app
